version: "3"

services:
  postgres-stepwise:
    image: postgres
    environment:
      - POSTGRES_DB=stepwise_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BUCKETS=mybucket
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
